info:
  description: Description from options
  termsOfService: http://tos.myweb.com
  title: Options title
  version: 6.0.7-beta
openapi: 3.0.0
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: private-token
      type: apiKey
security:
  - ApiKeyAuth: []
paths:
  /api/v4/namespaces:
    get:
      description: 'https://docs.gitlab.com/ee/api/namespaces.html#list-namespaces


        <br>


        *GET /namespaces*'
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: GET namespaces
      tags:
      - default
  /api/v4/projects:
    get:
      description: 'Docs: https://docs.gitlab.com/ee/api/projects.html#list-all-projects


        <br>


        *GET /projects*


        <br>


        |Parameter|Type|Required|Description|

        |---|---|---|---|

        |archived|boolean|no|Limit by archived status|

        |visibility|string|no|Limit by visibility public, internal, or private|

        |order_by|string|no|Return projects ordered by id, name, path, created_at,
        updated_at, or last_activity_at fields. repository_size, storage_size, or
        wiki_size fields are only allowed for admins. Default is created_at|

        |sort|string|no|Return projects sorted in asc or desc order. Default is desc|

        |search|string|no|Return list of projects matching the search criteria|

        |search_namespaces|boolean|no|Include ancestor namespaces when matching search
        criteria. Default is false|

        |simple|boolean|no|Return only limited fields for each project. This is a
        no-op without authentication as then only simple fields are returned.|

        |owned|boolean|no|Limit by projects explicitly owned by the current user|

        |membership|boolean|no|Limit by projects that the current user is a member
        of|

        |starred|boolean|no|Limit by projects starred by the current user|

        |statistics|boolean|no|Include project statistics|

        |with_custom_attributes|boolean|no|Include custom attributes in response (admins
        only)|

        |with_issues_enabled|boolean|no|Limit by enabled issues feature|

        |with_merge_requests_enabled|boolean|no|Limit by enabled merge requests feature|

        |with_programming_language|string|no|Limit by projects which use the given
        programming language|

        |wiki_checksum_failed|boolean|no| Limit projects where the wiki checksum calculation
        has failed (Introduced in GitLab Premium 11.2)|

        |repository_checksum_failed|boolean|no| Limit projects where the repository
        checksum calculation has failed (Introduced in GitLab Premium 11.2)|

        |min_access_level|integer|no|Limit by current user minimal access level|

        |id_after|integer|no|Limit results to projects with IDs greater than the specified
        ID|

        |id_before|integer|no|Limit results to projects with IDs less than the specified
        ID|

        |last_activity_after|datetime|no|Limit results to projects with last_activity
        after specified time. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ|

        |last_activity_before|datetime|no|Limit results to projects with last_activity
        before specified time. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ|

        |repository_storage|string|no|Limit results to projects stored on repository_storage.
        Available for admins only.|'
      parameters:
      - example: '1'
        in: query
        name: owned
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: GET projects (only owned by current user)
      tags:
      - default
  /api/v4/projects/{id}:
    get:
      description: 'Docs: https://docs.gitlab.com/ee/api/projects.html#list-all-projects


        <br>


        *GET /projects/:id*


        <br>


        |Parameter|Type|Required|Description|

        |---|---|---|---|

        |id|integer/string|yes|The ID or URL-encoded path of the project|

        |statistics|boolean|no|Include project statistics|

        |license|boolean|no|Include project license data|

        |with_custom_attributes|boolean|no|Include custom attributes in response (admins
        only)|'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: GET project by id
      tags:
      - default
  /api/v4/projects/{id}/pipelines:
    get:
      description: 'Docs: https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines


        <br>


        *GET /projects/:id/pipelines*


        <br>


        |Parameter|Type|Required|Description|

        |---|---|---|---|

        |id|integer/string|yes|The ID or URL-encoded path of the project owned by
        the authenticated user|

        |scope|string|no|The scope of pipelines, one of: running, pending, finished,
        branches, tags|

        |status|string|no|The status of pipelines, one of: created, waiting_for_resource,
        preparing, pending, running, success, failed, canceled, skipped, manual, scheduled|

        |ref|string|no|The ref of pipelines|

        |sha|string|no|The SHA of pipelines|

        |yaml_errors|boolean|no|Returns pipelines with invalid configurations|

        |name|string|no|The name of the user who triggered pipelines|

        |username|string|no|The username of the user who triggered pipelines|

        vupdated_after|datetime|no|Return pipelines updated after the specified date.
        Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ|

        |updated_before|datetime|no|Return pipelines updated before the specified
        date. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ|

        |order_by|string|no|Order pipelines by id, status, ref, updated_at or user_id
        (default: id)|

        |sort|string|no|Sort pipelines in asc or desc order (default: desc)|'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: GET pipelines
      tags:
      - default
  /api/v4/projects/{id}/repository/commits:
    get:
      description: "Docs: https://docs.gitlab.com/ee/api/commits.html\n\n<br>\n\n\
        *GET /projects/:id/repository/commits*\n\n<br>\n\n|Parameter|Type|Required|Description|\n\
        |---|---|---|---|\n|id|integer/string|yes|The ID or\_URL-encoded path of the\
        \ project\_owned by the authenticated user|\n|ref_name|string|no|The name\
        \ of a repository branch, tag or revision range, or if not given the default\
        \ branch|\n|since|string|no|Only commits after or on this date will be returned\
        \ in ISO 8601 format YYYY-MM-DDTHH:MM:SSZ|\n|until|string|no|Only commits\
        \ before or on this date will be returned in ISO 8601 format YYYY-MM-DDTHH:MM:SSZ|\n\
        |path|string|no|The file path|\n|all|boolean|no|Retrieve every commit from\
        \ the repository|\n|with_stats|boolean|no|Stats about each commit will be\
        \ added to the response|\n|first_parent|boolean|no|Follow only the first parent\
        \ commit upon seeing a merge commit|\n|order|string|no|List commits in order.\
        \ Possible values:\_default,\_topo. Defaults to\_default, the commits are\
        \ shown in reverse chronological order.|"
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: GET commits
      tags:
      - default
  /api/v4/projects/{id}/repository/commits/{sha}:
    get:
      description: 'Docs: https://docs.gitlab.com/ee/api/commits.html#get-a-single-commit


        <br>


        *GET /projects/:id/repository/commits/:sha*


        <br>


        |Parameter|Type|Required|Description|

        |---|---|---|---|

        |id|integer/string|yes|The ID or URL-encoded path of the project owned by
        the authenticated user|

        |sha|string|yes|The commit hash or name of a repository branch or tag|

        |stats|boolean|no|Include commit stats. Default is true|'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: path
        name: sha
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: GET commit by sha
      tags:
      - default
servers:
- url: http://{{api_url}}
